var classesTargetColors = {
    "CodeMirror ": "#FFF",
    "CodeMirror-lines ": "#FFF",
    "CodeMirror pre ": "#FFF",
    "CodeMirror-scrollbar-filler": "#FFF",
    "CodeMirror-gutter-filler ": "#FFF",
    "CodeMirror-gutters ": "#FFF",
    "CodeMirror-linenumbers ": "#FFF",
    "CodeMirror-linenumber ": "#FFF",
    "CodeMirror-guttermarker ": "#FFF",
    "CodeMirror-guttermarker-subtle ": "#FFF",
    "CodeMirror-cursor ": "#FFF",
    "CodeMirror div": "#FFF",
    "CodeMirror-secondarycursor ": "#FFF",
    "cm-fat-cursor ": "#FFF",
    "CodeMirror-cursor ": "#FFF",
    "cm-fat-cursor div": "#FFF",
    "CodeMirror-cursors ": "#FFF",
    "cm-fat-cursor-mark ": "#FFF",
    "cm-animate-fat-cursor ": "#FFF",
    "CodeMirror-overwrite ": "#FFF",
    "CodeMirror-cursor ": "#FFF",
    "cm-tab ": "#FFF",
    "CodeMirror-rulers ": "#FFF",
    "CodeMirror-ruler ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-header ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-quote ": "#FFF",
    "cm-negative ": "#FFF",
    "cm-positive ": "#FFF",
    "cm-header": "#FFF",
    "cm-strong ": "#FFF",
    "cm-em ": "#FFF",
    "cm-link ": "#FFF",
    "cm-strikethrough ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-keyword ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-atom ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-number ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-def ": "#00ff01",
    "cm-s-default ": "#FFF",
    "cm-variable": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-punctuation": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-property": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-operator ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-variable-2 ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-variable-3": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-type ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-comment ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-string ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-string-2 ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-meta ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-qualifier ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-builtin ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-bracket ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-tag ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-attribute ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-hr ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-link ": "#FFF",
    "cm-s-default ": "#FFF",
    "cm-error ": "#FFF",
    "cm-invalidchar ": "#FFF",
    "CodeMirror-composing ": "#FFF",
    "CodeMirror-matchingtag ": "#FFF",
    "CodeMirror-activeline-background ": "#FFF",
    "CodeMirror ": "#FFF",
    "CodeMirror-scroll ": "#FFF",
    "CodeMirror-sizer ": "#FFF",
    "CodeMirror-vscrollbar": "#FFF",
    "CodeMirror-hscrollbar": "#FFF",
    "CodeMirror-scrollbar-filler": "#FFF",
    "CodeMirror-gutter-filler ": "#FFF",
    "CodeMirror-vscrollbar ": "#FFF",
    "CodeMirror-hscrollbar ": "#FFF",
    "CodeMirror-scrollbar-filler ": "#FFF",
    "CodeMirror-gutter-filler ": "#FFF",
    "CodeMirror-gutters ": "#FFF",
    "CodeMirror-gutter ": "#FFF",
    "CodeMirror-gutter-wrapper ": "#FFF",
    "CodeMirror-gutter-background ": "#FFF",
    "CodeMirror-gutter-elt ": "#FFF",
    "CodeMirror-gutter-wrapper ::selection ": "#FFF",
    "CodeMirror-gutter-wrapper ::-moz-selection ": "#FFF",
    "CodeMirror-lines ": "#FFF",
    "CodeMirror pre ": "#FFF",
    "CodeMirror-wrap pre ": "#FFF",
    "CodeMirror-linebackground ": "#FFF",
    "CodeMirror-linewidget ": "#FFF",
    "CodeMirror-widget ": "#FFF",
    "CodeMirror-rtl pre ": "#FFF",
    "CodeMirror-code ": "#FFF",
    "CodeMirror-scroll": "#FFF",
    "CodeMirror-sizer": "#FFF",
    "CodeMirror-gutter": "#FFF",
    "CodeMirror-gutters": "#FFF",
    "CodeMirror-linenumber ": "#FFF",
    "CodeMirror-measure ": "#FFF",
    "CodeMirror-cursor ": "#FFF",
    "CodeMirror-measure pre ": "#FFF",
    "CodeMirror-focused div": "#FFF",
    "CodeMirror-cursors ": "#FFF",
    "CodeMirror-selected ": "#FFF",
    "CodeMirror-focused ": "#FFF",
    "CodeMirror-selected ": "#FFF",
    "CodeMirror-crosshair ": "#FFF",
    "CodeMirror-line::selection": "#FFF",
    "CodeMirror-line>span::selection": "#FFF",
    "CodeMirror-line>span>span::selection ": "#FFF",
    "CodeMirror-line::-moz-selection": "#FFF",
    "CodeMirror-line>span::-moz-selection": "#FFF",
    "CodeMirror-line>span>span::-moz-selection ": "#FFF",
    "cm-searching ": "#FFF",
    "cm-force-border ": "#FFF",
    "cm-tab-wrap-hack:after ": "#FFF",
    "CodeMirror-dialog ": "#FFF",
    "CodeMirror-dialog-top ": "#FFF",
    "CodeMirror-dialog-bottom ": "#FFF",
    "CodeMirror-dialog input ": "#FFF",
    "CodeMirror-dialog button ": "#FFF",
    "CodeMirror-fullscreen ": "#FFF",
    "CodeMirror-foldmarker ": "#FFF",
    "CodeMirror-foldgutter ": "#FFF",
    "CodeMirror-foldgutter-open": "#FFF",
    "CodeMirror-foldgutter-folded ": "#FFF",
    "CodeMirror-foldgutter-open:after ": "#FFF",
    "CodeMirror-foldgutter-folded:after ": "#FFF",
    "CodeMirror-hints ": "#FFF",
    "CodeMirror-hint ": "#FFF",
    "CodeMirror-completions ": "#FFF",
    "CodeMirror-completions select ": "#FFF",
    "CodeMirror-lint-markers ": "#FFF",
    "CodeMirror-lint-tooltip ": "#FFF",
    "CodeMirror-lint-mark-error": "#FFF",
    "CodeMirror-lint-mark-warning ": "#FFF",
    "CodeMirror-lint-mark-error ": "#FFF",
    "CodeMirror-lint-mark-warning ": "#FFF",
    "CodeMirror-lint-marker-error": "#FFF",
    "CodeMirror-lint-marker-warning ": "#FFF",
    "CodeMirror-lint-message-error": "#FFF",
    "CodeMirror-lint-message-warning ": "#FFF",
    "CodeMirror-lint-marker-error": "#FFF",
    "CodeMirror-lint-message-error ": "#FFF",
    "CodeMirror-lint-marker-warning": "#FFF",
    "CodeMirror-lint-message-warning ": "#FFF",
    "CodeMirror-lint-marker-multiple ": "#FFF",
    "CodeMirror-merge ": "#FFF",
    "CodeMirror-merge": "#FFF",
    "CodeMirror-merge ": "#FFF",
    "CodeMirror ": "#FFF",
    "CodeMirror-merge-2pane ": "#FFF",
    "CodeMirror-merge-pane ": "#FFF",
    "CodeMirror-merge-2pane ": "#FFF",
    "CodeMirror-merge-gap ": "#FFF",
    "CodeMirror-merge-3pane ": "#FFF",
    "CodeMirror-merge-pane ": "#FFF",
    "CodeMirror-merge-3pane ": "#FFF",
    "CodeMirror-merge-gap ": "#FFF",
    "CodeMirror-merge-pane ": "#FFF",
    "CodeMirror-merge-pane-rightmost ": "#FFF",
    "CodeMirror-merge-gap ": "#FFF",
    "CodeMirror-merge-scrolllock-wrap ": "#FFF",
    "CodeMirror-merge-scrolllock ": "#FFF",
    "CodeMirror-merge-copybuttons-left": "#FFF",
    "CodeMirror-merge-copybuttons-right ": "#FFF",
    "CodeMirror-merge-copy ": "#FFF",
    "CodeMirror-merge-copy-reverse ": "#FFF",
    "CodeMirror-merge-copybuttons-left ": "#FFF",
    "CodeMirror-merge-copy ": "#FFF",
    "CodeMirror-merge-copybuttons-right ": "#FFF",
    "CodeMirror-merge-copy ": "#FFF",
    "CodeMirror-merge-r-inserted": "#FFF",
    "CodeMirror-merge-l-inserted ": "#FFF",
    "CodeMirror-merge-r-deleted": "#FFF",
    "CodeMirror-merge-l-deleted ": "#FFF",
    "CodeMirror-merge-r-chunk ": "#FFF",
    "CodeMirror-merge-r-chunk-start ": "#FFF",
    "CodeMirror-merge-r-chunk-end ": "#FFF",
    "CodeMirror-merge-r-connect ": "#FFF",
    "CodeMirror-merge-l-chunk ": "#FFF",
    "CodeMirror-merge-l-chunk-start ": "#FFF",
    "CodeMirror-merge-l-chunk-end ": "#FFF",
    "CodeMirror-merge-l-connect ": "#FFF",
    "CodeMirror-merge-l-chunk": "#FFF",
    "CodeMirror-merge-r-chunk ": "#FFF",
    "CodeMirror-merge-l-chunk-start": "#FFF",
    "CodeMirror-merge-r-chunk-start ": "#FFF",
    "CodeMirror-merge-l-chunk-end": "#FFF",
    "CodeMirror-merge-r-chunk-end ": "#FFF",
    "CodeMirror-merge-collapsed-widget:before ": "#FFF",
    "CodeMirror-merge-collapsed-widget ": "#FFF",
    "CodeMirror-merge-collapsed-line ": "#FFF",
    "CodeMirror-gutter-elt ": "#FFF",
    "CodeMirror-merge ": "#FFF",
    "CodeMirror-merge": "#FFF",
    "CodeMirror-merge ": "#FFF",
    "CodeMirror ": "#FFF",
    "CodeMirror-merge-2pane ": "#FFF",
    "CodeMirror-merge-pane ": "#FFF",
    "CodeMirror-merge-2pane ": "#FFF",
    "CodeMirror-merge-gap ": "#FFF",
    "CodeMirror-merge-3pane ": "#FFF",
    "CodeMirror-merge-pane ": "#FFF",
    "CodeMirror-merge-3pane ": "#FFF",
    "CodeMirror-merge-gap ": "#FFF",
    "CodeMirror-merge-pane ": "#FFF",
    "CodeMirror-merge-pane-rightmost ": "#FFF",
    "CodeMirror-merge-gap ": "#FFF",
    "CodeMirror-merge-scrolllock-wrap ": "#FFF",
    "CodeMirror-merge-scrolllock ": "#FFF",
    "CodeMirror-merge-copybuttons-left": "#FFF",
    "CodeMirror-merge-copybuttons-right ": "#FFF",
    "CodeMirror-merge-copy ": "#FFF",
    "CodeMirror-merge-copy-reverse ": "#FFF",
    "Codemirror-moved-msg ": "#FFF",
    "CodeMirror-merge-copybuttons-left ": "#FFF",
    "CodeMirror-merge-copy ": "#FFF",
    "CodeMirror-merge-copybuttons-right ": "#FFF",
    "CodeMirror-merge-copy ": "#FFF",
    "CodeMirror-merge-r-inserted": "#FFF",
    "CodeMirror-merge-l-inserted ": "#FFF",
    "CodeMirror-merge-r-deleted": "#FFF",
    "CodeMirror-merge-l-deleted ": "#FFF",
    "CodeMirror-merge-r-chunk ": "#FFF",
    "CodeMirror-merge-r-chunk-start ": "#FFF",
    "CodeMirror-merge-r-chunk-end ": "#FFF",
    "CodeMirror-merge-r-connect ": "#FFF",
    "CodeMirror-merge-r-chunk-moved ": "#FFF",
    "CodeMirror-merge-l-chunk ": "#FFF",
    "CodeMirror-merge-l-chunk-moved ": "#FFF",
    "CodeMirror-merge-l-chunk-start ": "#FFF",
    "CodeMirror-merge-l-chunk-end ": "#FFF",
    "CodeMirror-merge-l-connect ": "#FFF",
    "CodeMirror-merge-l-chunk": "#FFF",
    "CodeMirror-merge-r-chunk ": "#FFF",
    "CodeMirror-merge-l-chunk-start": "#FFF",
    "CodeMirror-merge-r-chunk-start ": "#FFF",
    "CodeMirror-merge-l-chunk-end": "#FFF",
    "CodeMirror-merge-r-chunk-end ": "#FFF",
    "CodeMirror-merge-collapsed-widget:before ": "#FFF",
    "CodeMirror-merge-collapsed-widget ": "#FFF",
    "CodeMirror-merge-collapsed-line ": "#FFF",
    "CodeMirror-gutter-elt ": "#FFF",
    "CodeMirror-simplescroll-horizontal div": "#FFF",
    "CodeMirror-simplescroll-vertical div ": "#FFF",
    "CodeMirror-simplescroll-horizontal": "#FFF",
    "CodeMirror-simplescroll-vertical ": "#FFF",
    "CodeMirror-simplescroll-horizontal ": "#FFF",
    "CodeMirror-simplescroll-horizontal div ": "#FFF",
    "CodeMirror-simplescroll-vertical ": "#FFF",
    "CodeMirror-simplescroll-vertical div ": "#FFF",
    "CodeMirror-overlayscroll ": "#FFF",
    "CodeMirror-scrollbar-filler": "#FFF",
    "CodeMirror-overlayscroll ": "#FFF",
    "CodeMirror-gutter-filler ": "#FFF",
    "CodeMirror-overlayscroll-horizontal div": "#FFF",
    "CodeMirror-overlayscroll-vertical div ": "#FFF",
    "CodeMirror-overlayscroll-horizontal": "#FFF",
    "CodeMirror-overlayscroll-vertical ": "#FFF",
    "CodeMirror-overlayscroll-horizontal ": "#FFF",
    "CodeMirror-overlayscroll-horizontal div ": "#FFF",
    "CodeMirror-overlayscroll-vertical ": "#FFF",
    "CodeMirror-overlayscroll-vertical div ": "#FFF",
    "CodeMirror-search-match ": "#FFF",
    "CodeMirror-Tern-completion ": "#FFF",
    "CodeMirror-Tern-completion:before ": "#FFF",
    "CodeMirror-Tern-completion-unknown:before ": "#FFF",
    "CodeMirror-Tern-completion-object:before ": "#FFF",
    "CodeMirror-Tern-completion-fn:before ": "#FFF",
    "CodeMirror-Tern-completion-array:before ": "#FFF",
    "CodeMirror-Tern-completion-number:before ": "#FFF",
    "CodeMirror-Tern-completion-string:before ": "#FFF",
    "CodeMirror-Tern-completion-bool:before ": "#FFF",
    "CodeMirror-Tern-completion-guess ": "#FFF",
    "CodeMirror-Tern-tooltip ": "#FFF",
    "CodeMirror-Tern-hint-doc ": "#FFF",
    "CodeMirror-Tern-fname ": "#FFF",
    "CodeMirror-Tern-farg ": "#FFF",
    "CodeMirror-Tern-farg-current ": "#28ff37",
    "CodeMirror-Tern-type ": "#FFF",
    "CodeMirror-Tern-fhint-guess ": "#FFF",
};

var keys = Object.keys(classesTargetColors);
for (var i = 0; i < keys.length; i++) {
    try {
        var el = document.getElementsByClassName(keys[i]);
        el = el[0];
        el.style.backgroundColor = classesTargetColors[keys[i]];
    }
    catch (ex) {
        console.log("Failed to set code style: " + ex);
    }
}